### PR TITLE
[FW][IMP] Add amount residual currency in _search_filter_amount

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#281

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/283).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Pull request closed without merging**
