### PR TITLE
[FIX] l10n_ar_account_tax_settlement: arreglar txt ret iva sufridas

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Task: 31418
El nro de comprobante pasa a ser el nro de certificado y no el nro de orden de pago

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/211).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#234

**Pull request closed without merging**
