### PR TITLE
[IMP] l10n_ar_edi_ux: Change AFIP WS Padron

### PR DESCRIPTION
**Pull request by zaoral**
from ws_sr_padron_a5 to ws_sr_constancia_inscripcion

Manual backport
X-original-commit: 3ba9d78

### CODE REVIEW

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/214).

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc Ignore

**Pull request closed without merging**
