### PR TITLE
[FW][FIX] account_batch_payment_ux: fix depends of constraints method

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Debería hacerse un revert de este commit cuando Odoo haga un fix. Más info: https://www.odoo.com/es_ES/my/tasks/4296137

Forward-Port-Of: ingadhoc/odoo-argentina-ee#476

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/477).

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by cav-adhoc** [comment]
Se elimina la constraint del error para v18 acá: https://github.com/odoo/enterprise/pull/72388

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @cav-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
