### PR TITLE
[FW][IMP] l10n_ar_account_reports: show partner vat 

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket 47037

Forward-Port-Of: ingadhoc/odoo-argentina-ee#77

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/86).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @PabloPaezSheridan cherrypicking of pull request ingadhoc/odoo-argentina-ee#77 failed.

stdout:
```
Auto-merging l10n_ar_account_reports/models/__init__.py
CONFLICT (content): Merge conflict in l10n_ar_account_reports/models/__init__.py

```

stderr:
```
18:03:46.606640 git.c:439               trace: built-in: git cherry-pick 84116c302da8b7f4bc82e4b633357bae6ea8486a
error: could not apply 84116c3... [IMP] l10n_ar_account_reports: show partner vat
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-merge

**Comment by roboadhoc** [comment]
Merge method set to rebase and merge, using the PR as merge commit message

**Pull request closed without merging**
