### PR TITLE
[FW][FIX] account_journal_book_report: Fix print for huge numeber of entry's

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#102

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/103).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by nicomacr** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
