### PR TITLE
[FIX] l10n_ar_currency_update: disable test

### PR DESCRIPTION
**Pull request by zaoral**
We are getting an error in runbot that frezee the merge of other modules and PR. We disable temporally this test until we found a sustable solution to avoid the warning: `Incorrect usage of try_loading without a fully loaded registry. This could lead to issues. `

Ticket 82070

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/471).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#472

**Pull request closed without merging**
