### PR TITLE
[FIX] l10n_ar_edi_ux: Use sudo to access to model fields to avoid right errors.

### PR DESCRIPTION
**Pull request by nicomacr**
### Ticket 55037

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/138).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral, you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
