### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: arreglo en txt de iibb api

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 42953

Forward-Port-Of: ingadhoc/odoo-argentina-ee#454

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/456).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#454 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/models/account_journal.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/models/account_journal.py

```

stderr:
```
20:04:38.171142 git.c:444               trace: built-in: git cherry-pick d9a2aeb77278b0c9e45f1bea9bef601f1718a1c0
error: could not apply d9a2aeb... [FIX] l10n_ar_account_tax_settlement: arreglo en txt de iibb api
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba
we merge bevause runbot is yellow with a warning of an external error

**Pull request closed without merging**
