### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: percepciones Misiones. Importe de la operación

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 65802

Forward-Port-Of: ingadhoc/odoo-argentina-ee#265

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/267).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#265 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/models/account_journal.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/models/account_journal.py

```

stderr:
```
20:33:51.651859 git.c:444               trace: built-in: git cherry-pick e77fef5e3893f61daf30af3eb4d265583d3afe71
error: could not apply e77fef5... [FIX] l10n_ar_account_tax_settlement: percepciones Misiones. Importe de la operación
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
