### PR TITLE
[FIX]account_tax_settlement: optimizar el dominio de account.payment group para tenes en cuenta las líneas a pagar

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 57510

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/167).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
