### PR TITLE
[FW][FIX]l10n_ar_currency_update: fix currency if currency ARS name is ch…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…anged

Ticket: 51623

Forward-Port-Of: ingadhoc/odoo-argentina-ee#104

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/105).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral

ci/oba_without_tests failed on this forward-port PR

**Comment by zaoral** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
