### PR TITLE
[FIX] l10n_ar_currency_update: update currency rates when there are c…

### PR DESCRIPTION
**Pull request by pablohmontenegro**
…ompanies with expired digital certificate (afip)

Ticket: 62824

Cuando tenemos una compañía que tiene realizada la configuración para sincronizar tasas de cambio con afip y la misma no tiene certificado digital, estábamos buscando una compañía que lo tenga. Pero la compañía que lo tiene puede tener el certificado expirado; en ese caso tenemos un conflicto porque no se terminan actualizando las tasas. En este commit lo que hacemos es buscar una compañía que tenga certificado y no esté expirado.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/228).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#229
- ingadhoc/odoo-argentina-ee#230

**Pull request closed without merging**
