### PR TITLE
[FIX] l10n_ar_account_tax_settlement: avoid returning None

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/235).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#239

**Pull request closed without merging**
