### PR TITLE
[FW][FIX]l10n_ar_account_reports: Replace t tag for span tag to fix error when reporting checks to date

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#352
Forward-Port-Of: ingadhoc/odoo-argentina-ee#340

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/353).

**Comment by fw-bot-adhoc** [comment]
@lucianobaleani @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#340 failed.

stdout:
```
Auto-merging l10n_ar_account_reports/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_reports/__manifest__.py

```

stderr:
```
15:14:05.650383 git.c:444               trace: built-in: git cherry-pick 2c3675fb6a6bd5883a1f17d6101e0aaeecd189c9
error: could not apply 2c3675f... [FIX]l10n_ar_account_reports: Replace t tag for span tag to fix error when reporting checks to date
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
we heave external runbot error.
Already fixed so we retry a new build.
This should be merged in a couple of minutes

**Comment by zaoral** [comment]
@roboadhoc retry

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: retry makes no sense when the PR is not in error.

**Pull request closed without merging**
