### PR TITLE
[FW][REM] l10n_ar_edi_ux: Remove fixture of debit check

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#493

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/499).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @jjscarafia cherrypicking of pull request ingadhoc/odoo-argentina-ee#493 failed.

stdout:
```
Removing l10n_ar_edi_ux/wizards/account_check_action_wizard_view.xml
Removing l10n_ar_edi_ux/wizards/account_check_action_wizard.py
Removing l10n_ar_edi_ux/views/account_payment_view.xml
Removing l10n_ar_edi_ux/models/account_payment.py
Auto-merging l10n_ar_edi_ux/i18n/es.po
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/i18n/es.po
Auto-merging l10n_ar_edi_ux/__manifest__.py

```

stderr:
```
14:59:14.420440 git.c:444               trace: built-in: git cherry-pick fc8509b8bbaf1512a4ce31f8c8bc58ebb1a84f23
error: could not apply fc8509b... [REM] l10n_ar_edi_ux: Remove fixture of debit check
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
