### PR TITLE
[FIX] account_tax_settlement: get only journals ids in report

### PR DESCRIPTION
**Pull request by cav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/367).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@cav-adhoc @maq-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
