### PR TITLE
[FW][FIX] l10n_ar_currency_update: l10n_ar_last_currency_sync_date when ar rates are not created

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 84697

Forward-Port-Of: ingadhoc/odoo-argentina-ee#505

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/510).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral the next pull request (ingadhoc/odoo-argentina-ee#511) is in conflict. You can merge the chain up to here by saying
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
