### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: Percepciones iibb Santa Fe Aplicada

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 64814
Cuando se generar el txt de percepciones iibb Santa Fe Aplicada y se sube el txt correspondiente al aplicativo de siprib de siap lo que sucede es que no acepta punto de venta de 5 dígitos, por lo tanto se realiza cambio para que tome solamente 4 dígitos y además el importe base de cálculo que se estaba contemplado era incorrecto, se estaba tomando la base no gravada y necesitamos que tome en cuenta como base del impuesto el monto gravado.

Forward-Port-Of: ingadhoc/odoo-argentina-ee#263

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/269).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-argentina-ee#268

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro:
- this PR is already reviewed, reviewing it again is useless.
- you are not allowed to override this status.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ override=ci/oba

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro:
- this PR is already reviewed, reviewing it again is useless.
- you are not allowed to override this status.

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
