### PR TITLE
[IMP] Add amount residual currency in _search_filter_amount

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/281).

**Review by ica-adhoc — APPROVED** [review]

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#283

**Pull request closed without merging**
