### PR TITLE
[IMP] Add to readme de link where currency rates can be checked

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 50492

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/99).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/99).

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
