### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 28323

Forward-Port-Of: ingadhoc/odoo-argentina-ee#172

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/175).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#172 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/data/inflation_adjustment_index.xml
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/data/inflation_adjustment_index.xml
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
21:13:35.261920 git.c:444               trace: built-in: git cherry-pick 33156fff7d816370a6b37e70d0679abc91855bb6
error: could not apply 33156ff... [IMP] l10n_ar_account_tax_settlement: update inflation indexes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@pablohmontenegro you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Pull request closed without merging**
