### PR TITLE
[FIX] account_tax_settlement: get company context in default get off …

### PR DESCRIPTION
**Pull request by maq-adhoc**
…account.tax.settlement.wizard

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/306).

**Comment by rov-adhoc** [comment]
@roboadhoc r+ rebase-ff

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc ignore

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Pull request closed without merging**
