### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: error cuando una percepción no tiene partner asociado

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 66860

Forward-Port-Of: ingadhoc/odoo-argentina-ee#274

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/280).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
