### PR TITLE
[IMP] l10n_ar_account_tax_settlement: Se creo el metodo get_account_id

### PR DESCRIPTION
**Pull request by mem-adhoc**
Task: 28331

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/166).

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/166).

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#173
- ingadhoc/odoo-argentina-ee#174

**Pull request closed without merging**
