### PR TITLE
[FW][FIX] l10n_ar_currency_update: l10n_ar_last_currency_sync_date when ar rates are not created

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 84697

Forward-Port-Of: ingadhoc/odoo-argentina-ee#505

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/511).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#505 failed.

stdout:
```
Auto-merging l10n_ar_currency_update/models/res_company.py
CONFLICT (content): Merge conflict in l10n_ar_currency_update/models/res_company.py

```

stderr:
```
20:37:08.037395 git.c:444               trace: built-in: git cherry-pick aea00891f5bb86f8465f5af927c5429fb22ea009
error: could not apply aea0089... [FIX] l10n_ar_currency_update: l10n_ar_last_currency_sync_date when ar rates are not created
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@roboadhoc  r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
