### PR TITLE
[FIX] account_accountant_ux: journal dashboard

### PR DESCRIPTION
**Pull request by ica-adhoc**
Now the Balance in GL calculate correctly

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/307).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#308

**Pull request closed without merging**
