### PR TITLE
[FW][FIX] l10n_ar_edi_ux: Se reintegra un campo que fue borrado por error

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 28319
Reintegramos el campo arba_cit que fue borrado por error

Forward-Port-Of: ingadhoc/odoo-argentina-ee#330

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/331).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
not changes, only rebases

@roboadhoc r+

**Pull request closed without merging**
