### PR TITLE
[FW] Revert "[ADD] l10n_ar_edi_ux: mejora de rendimiento en actualizacion …

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…masiva de partners"

This reverts commit bb3bb71dcdc00eb24c99683c71d3eaa5ed7dc19a.

Forward-Port-Of: ingadhoc/odoo-argentina-ee#397

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/398).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @maq-adhoc cherrypicking of pull request ingadhoc/odoo-argentina-ee#397 failed.

stdout:
```
Auto-merging l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard_view.xml
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard_view.xml
Auto-merging l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/wizards/res_partner_update_from_padron_wizard.py
Auto-merging l10n_ar_edi_ux/views/res_partner_view.xml
Auto-merging l10n_ar_edi_ux/models/res_partner.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/models/res_partner.py
Auto-merging l10n_ar_edi_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/__manifest__.py

```

stderr:
```
17:58:41.080508 git.c:444               trace: built-in: git cherry-pick 4daf5a2499933163a1fbb55d5bd4f2da6ea067c2
error: could not apply 4daf5a2... Revert "[ADD] l10n_ar_edi_ux: mejora de rendimiento en actualizacion masiva de partners"
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
Cierro porque solo hay que revertir en 16. La mejora la dejamos en 17

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
