### PR TITLE
[ADD] l10n_ar_edi_ux: new/legacy padron compatible

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/220).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by zaoral** [comment]
cancelamos ya que no vamos a soportar la version legacy.
que se muden los clientes al ws nuevo

**Pull request closed without merging**
