### PR TITLE
[FIX] l10n_ar_account_tax_settlement: Use Date instead "payment date" for a payment

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/158).

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Comment by fw-bot-adhoc** [comment]
@nicomacr @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#159

**Pull request closed without merging**
