### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#147

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/148).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#147 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/data/inflation_adjustment_index.xml
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/data/inflation_adjustment_index.xml
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
19:05:36.038377 git.c:439               trace: built-in: git cherry-pick a78cc411a4f7793c7676182d3814fddf43274d1f
error: could not apply a78cc41... [IMP] l10n_ar_account_tax_settlement: update inflation indexes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
resolve conflict, and merge

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
