### PR TITLE
[REF] l10n_ar_demo: re-add checks

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/73).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc p=1 override=ci/personalizations

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Pull request closed without merging**
