### PR TITLE
[FW][REF] l10n_ar_edi_ux: remove check_debit_journal_id

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#360

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/362).

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @jjscarafia cherrypicking of pull request ingadhoc/odoo-argentina-ee#360 failed.

stdout:
```
Auto-merging l10n_ar_edi_ux/wizards/account_check_action_wizard.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/wizards/account_check_action_wizard.py
Auto-merging l10n_ar_edi_ux/views/account_payment_view.xml
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/views/account_payment_view.xml
Auto-merging l10n_ar_edi_ux/views/account_journal_view.xml
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/views/account_journal_view.xml
Auto-merging l10n_ar_edi_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/__manifest__.py

```

stderr:
```
13:39:05.313001 git.c:444               trace: built-in: git cherry-pick ae3de570117c38442496fa6fd21502973da7c6e7
error: could not apply ae3de57... [REF] l10n_ar_edi_ux: remove check_debit_journal_id
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by cav-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@cav-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
