### PR TITLE
[FW][ADD] l10n_ar_ux: Data on activities, taxes and concepts is create

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 28319

Forward-Port-Of: ingadhoc/odoo-argentina-ee#293

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/313).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
FYI
the pr has not changed, only made a rebase
@roboadhoc r+

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
