### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: ticket 52458

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
sanitize vat in agip files

Forward-Port-Of: ingadhoc/odoo-argentina-ee#117

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/118).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral, @jjscarafia
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
