### PR TITLE
[FW][REF] l10n_ar_account_tax_settlement: extend sifere help info

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 51981

Forward-Port-Of: ingadhoc/odoo-argentina-ee#109

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/110).

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
Ping @zaoral

ci/oba_without_tests failed on this forward-port PR

**Review by zaoral — APPROVED** [review]

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
