### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 28323
Add inflation indexes october and november 2023 from https://www.facpce.org.ar/indices-facpce/ "Indice RT 6"

Forward-Port-Of: ingadhoc/odoo-argentina-ee#298

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/299).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#298 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
12:49:55.016299 git.c:444               trace: built-in: git cherry-pick 983c80dec01ef3a3b39359ce6d98dd40aa79a3e9
error: could not apply 983c80d... [IMP] l10n_ar_account_tax_settlement: update inflation indexes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
