### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: txt sircar arreglar error descarga txt notas de crédito

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 63994

Forward-Port-Of: ingadhoc/odoo-argentina-ee#243

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/245).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this PR targets 16.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-argentina-ee#244

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
