### PR TITLE
[FIX] l10n_ar_account_tax_settlement: error descarga txt percep misiones

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 64478
fp directo de 13 a 16 creado manualmente.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/255).

**Comment by ica-adhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@ica-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @ica-adhoc: you are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
