### PR TITLE
[IMP] l10n_ar_account_tax_settlement: contemplar base de cálculo retenciones de iva en txt sicore aplicado

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Task: 29675

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/185).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#186
- ingadhoc/odoo-argentina-ee#187

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#186
- ingadhoc/odoo-argentina-ee#187

**Pull request closed without merging**
