### PR TITLE
[FIX] account_accountant_ux: fix filter by same amount

### PR DESCRIPTION
**Pull request by cav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/374).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#423

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#423

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#423

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#423

**Pull request closed without merging**
