### PR TITLE
[MIG] l10n_ar_edi_ux: Migration to 16.0

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/150).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia @jcadhoc linked pull request(s) ingadhoc/odoo-argentina#654 not ready. Linked PRs are not staged until all of them are ready.

**Comment by roboadhoc** [comment]
@jjscarafia @jcadhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by jjscarafia** [comment]
@roboadhoc p=0

**Pull request closed without merging**
