### PR TITLE
[FIX] account_accountant_ux: update _get_followup_report_lines

### PR DESCRIPTION
**Pull request by cav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/441).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@cav-adhoc @rov-adhoc linked pull request(s) ingadhoc/multi-company#164 not ready. Linked PRs are not staged until all of them are ready.

**Comment by cav-adhoc** [comment]
sigue en https://github.com/ingadhoc/odoo-argentina-ee/pull/442

**Pull request closed without merging**
