### PR TITLE
[ADD] l10n_ar_edi_ux: Adapting the zeep library

### PR DESCRIPTION
**Pull request by mem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/403).

**Review by zaoral — CHANGES_REQUESTED** [review]
Hi @mem-adhoc !
Thank you for the fix

You will also need to remove the external python import from manifest
https://github.com/ingadhoc/odoo-argentina-ee/blob/95251a32bded98e5f6cec90c6070c7df009db6a9/l10n_ar_edi_ux/__manifest__.py#L13-L16

**Comment by mem-adhoc** [comment]
@zaoral Hi Kathy, thank you for the review!
I made the changes you asked me for!
Greetings!

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
