### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: contemplar base de cálculo retenciones de iva en txt sicore aplicado

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 29675

Forward-Port-Of: ingadhoc/odoo-argentina-ee#185

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/186).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 16.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
