### PR TITLE
[FW][IMP] Move bach payment edit to account_batch_payment_ux

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#359

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/369).

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
