### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: Error in branch create

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#446

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/452).

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @rov-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by vib-adhoc** [comment]
Ro, cerramos esto y mezclamos acá https://github.com/ingadhoc/odoo-argentina-ee/pull/453 porque se crearon algunos FW pero no todos.

**Pull request closed without merging**
