### PR TITLE
[FW][FIX] l10n_ar_account_reports: check_to_date

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
ticket 53256
---

Now the company is printed correctly in the checks to date report

Forward-Port-Of: ingadhoc/odoo-argentina-ee#134

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/135).

**Comment by fw-bot-adhoc** [comment]
Ping @ica-adhoc, @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#134 failed.

stdout:
```
CONFLICT (modify/delete): l10n_ar_account_reports/reports/report_checks_to_date.xml deleted in HEAD and modified in 0938fc5... [FIX] l10n_ar_account_reports: check_to_date. Version 0938fc5... [FIX] l10n_ar_account_reports: check_to_date of l10n_ar_account_reports/reports/report_checks_to_date.xml left in tree.
Auto-merging l10n_ar_account_reports/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_reports/__manifest__.py

```

stderr:
```
13:19:58.533643 git.c:439               trace: built-in: git cherry-pick 0938fc5ffe1e44eadb5fe73c1fa7b0a241b2949d
error: could not apply 0938fc5... [FIX] l10n_ar_account_reports: check_to_date
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by ica-adhoc** [comment]
@jjscarafia FW relacionado con cheques, se cierra?

**Comment by zaoral** [comment]
review with juan @jjscarafia

**Comment by zaoral** [comment]
@ica-adhoc 
Hi Nachito.
Please give priority to this pr
if you need help we can work it together.

Best Regards

**Comment by ica-adhoc** [comment]
superseded by https://github.com/ingadhoc/odoo-argentina-ee/pull/188

**Pull request closed without merging**
