### PR TITLE
[MIG] l10n_ar_edi_ux: Migration to 15.0

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/67).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests override=ci/argentina-ee

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Pull request closed without merging**
