### PR TITLE
[FIX] l10n_ar_account_tax_settlement: txt sircar arreglar error descarga txt notas de crédito

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 63994

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/243).

**Comment by ica-adhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @ica-adhoc: you are not allowed to override this status.

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#244
- ingadhoc/odoo-argentina-ee#245

**Pull request closed without merging**
