### PR TITLE
[IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Task: 28323

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/189).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#194

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @mem-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#194

**Pull request closed without merging**
