### PR TITLE
[ADD] account_accountant_ux: restore Balance in GL

### PR DESCRIPTION
**Pull request by ica-adhoc**
restore Balance in GL data on account journal dashboard

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/294).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#295

**Pull request closed without merging**
