### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 28323

Forward-Port-Of: ingadhoc/odoo-argentina-ee#218
Forward-Port-Of: ingadhoc/odoo-argentina-ee#209

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/219).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#209 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
18:25:01.858575 git.c:444               trace: built-in: git cherry-pick 7c1beb58a18e0876ad547712b17392d23886d76b
error: could not apply 7c1beb5... [IMP] l10n_ar_account_tax_settlement: update inflation indexes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
