### PR TITLE
13.0 fix journals demo2

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/81).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by jjscarafia** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Pull request closed without merging**
