### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: sicore aplicado iva percepciones

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 47086.Generates the txt file for sicore IVA applied insights

Forward-Port-Of: ingadhoc/odoo-argentina-ee#82

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/92).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#82 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/models/account_journal.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/models/account_journal.py
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
00:05:34.785048 git.c:439               trace: built-in: git cherry-pick 155fbe3d9348d52291eda87933b37664f630c462
error: could not apply 155fbe3... [IMP] l10n_ar_account_tax_settlement: sicore aplicado iva percepciones
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
@roboadhoc +r

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
