### PR TITLE
[FW][FIX] account_accountant_ux: fix filter by same amount

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ee#374

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/423).

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @maq-adhoc cherrypicking of pull request ingadhoc/odoo-argentina-ee#374 failed.

stdout:
```
Auto-merging account_accountant_ux/models/account_move_line.py
CONFLICT (content): Merge conflict in account_accountant_ux/models/account_move_line.py

```

stderr:
```
12:38:49.188444 git.c:444               trace: built-in: git cherry-pick 9a82f767dc761a8134f788b04d8b91982170ac6b
error: could not apply 9a82f76... [FIX] account_accountant_ux: fix filter by same amount
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by cav-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
