### PR TITLE
[FW][FIX] l10n_ar_edi_ux: We consider whether the surname or first name data is empty

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 29136

Forward-Port-Of: ingadhoc/odoo-argentina-ee#363

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/501).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR targets 18.0 and is the last of the forward-port chain containing:
* ingadhoc/odoo-argentina-ee#500

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
