### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: arreglo en txt de iibb api

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 42953

Forward-Port-Of: ingadhoc/odoo-argentina-ee#454

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/455).

**Comment by fw-bot-adhoc** [comment]
This PR targets 16.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
NOTE: Do not need to generaete to 17. already solved in that version

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral the next pull request (ingadhoc/odoo-argentina-ee#456) is in conflict. You can merge the chain up to here by saying
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Pull request closed without merging**
