### PR TITLE
[ADD] l10n_ar_account_tax_settlement: agregar tags y configuraciones a impuestos.

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Tarea: 40361

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/416).

**Comment by mem-adhoc** [comment]
Hi !
@pablohmontenegro Could you rebase this PR? so we can merge it

**Comment by pablohmontenegro** [comment]
@mem-adhoc ready, thanks!

**Comment by mem-adhoc** [comment]
Hi @pablohmontenegro!
The tests are not done yet, can you rebase again?
Weirdly, it is still loading, they must be finished.

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
