### PR TITLE
[FIX] l10n_ar_currency_update: currency rate

### PR DESCRIPTION
**Pull request by zaoral**
ticket 46686
---

Before this change, we were creating the currency with the date return by AFIP webservice, but instead, we should use that day + 1 in order to properly reuse the rate for creating invoices in the past.

A 24/11 invoice date should use the 23/11 rate, not the 24/11 rate. The 24/11 rate is actually generated the 25/11. Now to fix it and avoid all this confusion we only set the date and the available rate that can be used: so we still have in odoo 24/11 rate that actually is the one generated the 23/11 and that is the one currently active.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/63).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#64

**Pull request closed without merging**
