### PR TITLE
[FW][FIX] l10n_ar_currency_update: disable test

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
We are getting an error in runbot that frezee the merge of other modules and PR. We disable temporally this test until we found a sustable solution to avoid the warning: `Incorrect usage of try_loading without a fully loaded registry. This could lead to issues. `

Ticket 82070

Forward-Port-Of: ingadhoc/odoo-argentina-ee#471

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/472).

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
Hello @zaoral , do we need to merge this fw?

**Comment by zaoral** [comment]
We can cancel this, 18 test is running ok

**Pull request closed without merging**
