### PR TITLE
[FW][FIX]account_journal_book_report:print amounts on debit column

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 53297
---

El problema se debía a que cuando se consultaban los move_id a imprimir se consultaba los objetos del reporte y no los moves a imprimir.

Forward-Port-Of: ingadhoc/odoo-argentina-ee#133

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/136).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
rebase, merge

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/oba_without_tests override=ci/argentina-ee

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro:
- you are not allowed to override this status.
- you are not allowed to override this status.

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by nicomacr** [comment]
@roboadhoc r+ override=ci/oba_without_tests p=0

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Pull request closed without merging**
