### PR TITLE
[FIX] l10n_ar_account_reports: check_to_date

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 53256
---

Now the company is printed correctly in the checks to date report

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/134).

**Comment by zaoral** [comment]
@roboadhoc r+

**Review by zaoral — APPROVED** [review]

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/odoo-argentina-ee#135

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ee#135

**Pull request closed without merging**
