### PR TITLE
[FIX] l10n_ar_edi_ux: Permitir a todos los usaurios utilizar el boton update from afip

### PR DESCRIPTION
**Pull request by mem-adhoc**
Task: 71093

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/323).

**Review by zaoral — CHANGES_REQUESTED** [review]
[cambios.txt](https://github.com/ingadhoc/odoo-argentina-ee/files/14213691/cambios.txt)

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#324

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#324

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ee#324

**Pull request closed without merging**
