### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: update inflation indexes

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 24871

Forward-Port-Of: ingadhoc/odoo-argentina-ee#155

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/156).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#155 failed.

stdout:
```
Auto-merging l10n_ar_account_tax_settlement/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_account_tax_settlement/__manifest__.py

```

stderr:
```
18:55:43.504910 git.c:439               trace: built-in: git cherry-pick 21461bb691495e605a0355b34b8c84f147112413
error: could not apply 21461bb... [IMP] l10n_ar_account_tax_settlement: update inflation indexes
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by zaoral** [comment]
we close it because has been already resolved in FW merged on https://github.com/ingadhoc/odoo-argentina-ee/pull/175

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/156).

**Pull request closed without merging**
