### PR TITLE
[FW][FIX] l10n_ar_edi_ux: Permitir a todos los usaurios utilizar el boton update from afip

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 71093

Forward-Port-Of: ingadhoc/odoo-argentina-ee#323

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/324).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#323 failed.

stdout:
```
Auto-merging l10n_ar_edi_ux/models/res_partner.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/models/res_partner.py

```

stderr:
```
20:09:15.232654 git.c:444               trace: built-in: git cherry-pick f62398d52414ef51b2d76a35e8922030fd51f005
error: could not apply f62398d... [FIX] l10n_ar_edi_ux: Permitir a todos los usaurios utilizar el oton update from afip
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
please @mem-adhoc 
fix this fw and merge it.
Best Regards

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
