### PR TITLE
[FW][FIX]account_accountant_ux:order account_followup lines by account mo…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…ve date

Ticket: 51895

Forward-Port-Of: ingadhoc/odoo-argentina-ee#116

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ee/pull/120).

**Comment by fw-bot-adhoc** [comment]
Ping @pablohmontenegro, @zaoral
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
need to do a rebase and the approve directly

**Comment by fw-bot-adhoc** [comment]
This PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro. This PR is already reviewed, reviewing it again is useless.

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
