### PR TITLE
[FW][IMP] l10n_ar_account_tax_settlement: nueva especificación txt iibb Misiones ret/perc

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 60295

Forward-Port-Of: ingadhoc/odoo-argentina-ee#191

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/221).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 16.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Pull request closed without merging**
