### PR TITLE
[FW][FIX] l10n_ar_account_tax_settlement: arreglo en txt de iibb api

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Tarea: 42953

Forward-Port-Of: ingadhoc/odoo-argentina-ee#456
Forward-Port-Of: ingadhoc/odoo-argentina-ee#454

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/469).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @zaoral this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Pull request closed without merging**
