### PR TITLE
[FW][FIX] l10n_ar_edi_ux: The buttons are being deleted due to disuse.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task: 28319

Forward-Port-Of: ingadhoc/odoo-argentina-ee#275

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/312).

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral cherrypicking of pull request ingadhoc/odoo-argentina-ee#275 failed.

stdout:
```
CONFLICT (modify/delete): l10n_ar_edi_ux/wizards/res_config_settings.py deleted in c5df7be ([FIX] l10n_ar_edi_ux: The buttons are being deleted due to disuse.) and modified in HEAD. Version HEAD of l10n_ar_edi_ux/wizards/res_config_settings.py left in tree.
Auto-merging l10n_ar_edi_ux/wizards/__init__.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/wizards/__init__.py
Auto-merging l10n_ar_edi_ux/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_edi_ux/__manifest__.py

```

stderr:
```
22:44:10.038402 git.c:444               trace: built-in: git cherry-pick c5df7beaf09519335adb0b1f1ed5b0129e2f4729
error: could not apply c5df7be... [FIX] l10n_ar_edi_ux: The buttons are being deleted due to disuse.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by zaoral** [comment]
@mem-adhoc 
Hi Maxi! please could you resolve the conflict and merge the PR?
Bwst Regards

**Comment by mem-adhoc** [comment]
@zaoral Hi Kathy, I hope you are doing well!
I fixed the conflicts in this PR but now it seems like does not have any changes. Could you help me?

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
