### PR TITLE
[ADD] l10n_ar_edi_ux: compatibility with module subchange

### PR DESCRIPTION
**Pull request by zaoral**
Be able to auto complete the missing required EDI values when the subchange is automatically created because of the use of financial plan

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/179).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
