### PR TITLE
[FW][IMP]l10n_ar_account_tax_settlement: retenciones y percepciones IVA txt

### PR DESCRIPTION
**Pull request by pablohmontenegro**
cierro fp https://github.com/ingadhoc/odoo-argentina-ee/pull/208

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ee/pull/246).

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@ica-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Comment by ica-adhoc** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @ica-adhoc: you are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
